apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-apps
  namespace: user1-argocd
spec:
  generators:
    - list:
        elements:
          - app: app1
            env: prod
          - app: app1
            env: dev
          - app: app2
            env: prod    
  template:
    metadata:
      name: '{{app}}-{{env}}'
      namespace: user1-argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/VictorFernandezArias/poc-gitops-resources.git
        targetRevision: main
        path: helm
        helm:
          valueFiles:
           - values-{{env}}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: poc-clh-6