apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
spec:
  destination:
    name: ''
    namespace: poc-clh-5
    server: 'https://kubernetes.default.svc'
  source:
    path: namespace-1
    repoURL: https://github.com/VictorFernandezArias/poc-gitops-apps.git
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
