apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app-of-apps
  namespace: user1-argocd
spec:
  destination:
    name: ''
    namespace: poc-clh
    server: 'https://kubernetes.default.svc'
  source:
    path: microservice01
    repoURL: https://github.com/VictorFernandezArias/poc-gitops-apps.git
    targetRevision: main
    directory:
      recurse: true
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
