apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app
  namespace: user1-argocd # Especificar el namespace de ArgoCD. Necesario si es controlado por otra app.
spec:
  destination:
    name: ''
    namespace: poc-clh-5
    server: 'https://kubernetes.default.svc'
  sources: 
  - path: helm
    repoURL: https://github.com/VictorFernandezArias/poc-gitops-resources.git
    targetRevision: main
    helm:
      valueFiles:
      - $values/values-prod.yaml
  - ref: values
    repoURL: https://github.com/VictorFernandezArias/poc-gitops-github-values.git
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
