apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app-credweb-api-pdf-convertions
  namespace: user1-argocd
spec:
  destination:
    name: ''
    namespace: poc-clh
    server: 'https://kubernetes.default.svc'
  source: 
    path: credweb-api-pdf-convertions
    repoURL: https://github.com/VictorFernandezArias/poc-gitops-helm-credito-web.git
    targetRevision: main
    helm:
      valueFiles:
      - values-prod.yaml
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
